name: Android 12L Build

on:
  push:
    branches:
      - main  # Trigger the build when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for building

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Clone the repository

      - name: Set up JDK
        uses: actions/setup-java@v2  # Set up Java (required for Android build)
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Use AdoptOpenJDK for Java

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y repo git python3  # Install dependencies like repo, git, and python3

      - name: Initialize Repo
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-12l  # Initialize the repo for Android 12L
          repo sync  # Sync the repository to get the latest source code

      - name: Set up the build environment
        run: |
          source build/envsetup.sh  # Set up the build environment

      - name: Choose build target
        run: |
          lunch aosp_x86-eng  # Choose the target build configuration (for x86)

      - name: Build Android 12L
        run: |
          make -j$(nproc)  # Build Android with all available CPU cores
