name: Android 12L Build

on:
  push:
    branches:
      - main  # Trigger the build when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for building

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v2  # Clone the repository

      # Step 2: Set up JDK (Java 11, using Zulu JDK)
      - name: Set up JDK
        uses: actions/setup-java@v2  # Set up Java (required for Android build)
        with:
          java-version: '11'
          distribution: 'zulu'  # Use Zulu JDK for Java 11

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y repo git python3  # Install dependencies like repo, git, and python3

      # Step 4: Initialize the Repo for Android 12L with correct branch
      - name: Initialize Repo
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1  # Correct branch for Android 12L
          repo sync  # Sync the repository to get 
